# Generated by Django 4.2.4 on 2023-09-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transactiongroup_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiongroup',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactiongroup',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
